name: Build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-application:
    name: Build library
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - uses: actions/setup-java@v4
        name: Set up JDK
        with:
          java-version: 21
          distribution: zulu

      - uses: gradle/actions/setup-gradle@v4
        name: Set up Gradle
        with:
          dependency-graph: generate-and-submit
          dependency-graph-continue-on-failure: true

      - name: Build binary
        run: ./gradlew build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_DEPENDENCY_GRAPH_JOB_ID: ${{ github.run_id }}
          GITHUB_DEPENDENCY_GRAPH_JOB_CORRELATOR: ${{ env.IMAGE_NAME }}
          GITHUB_DEPENDENCY_GRAPH_REF: ${{ github.ref }}
          GITHUB_DEPENDENCY_GRAPH_SHA: ${{ github.sha }}
          GITHUB_DEPENDENCY_GRAPH_WORKSPACE: ${{ github.workspace }}

      - name: Publish to Maven
        run: ./gradlew publish
        env:
          GITHUB_DEPENDENCY_GRAPH_ENABLED: false
        continue-on-error: true

      - uses: actions/upload-artifact@v4
        name: Upload build artifacts
        with:
          name: artifacts
          path: build/libs
        continue-on-error: true